### ISSUE TITLE
The "unneeded" roslib imports are actually needed.

### ISSUE THREAD

**Issue by bduffany** [ros-drivers/rosserial#28]
The recent commit for rosserial_python, SerialClient.py, why did you delete that roslib import line? When trying to run the hello world program, I got an error saying "failed to create publisher: global name 'roslib' is not defined" and the publisher wouldn't be created. I had to manually reinsert that line to get the program to work correctly. Can you put it back in there to prevent problems for other people?

**Comment by mikeferguson** [comment]
Fixed in https://github.com/ros-drivers/rosserial/commit/e41ea0c395893d7a537cb8c9f218b664ed9b8a16

**Comment by bduffany** [comment]
Thanks! But are you sure you shouldn't also add back the part that says

roslib.load_manifest("rosserial_python")

?

**Comment by mikeferguson** [comment]
Yes. These packages are catkinized. Under catkin, you no longer need to load the manifest, as all of the dependencies are already on the PYTHON_PATH. See http://ros.org/reps/rep-0122.html, specifically the section entitled "PYTHONPATH, roslib.load_manifest()"

**Comment by mikeferguson** [comment]
Also, just as a note. The currently catkinized/rospack-ed version is generating most messages correctly again (the version released for Fuerte had numerous problems due to parts of roslib being deprecated) -- however, the python node still uses load_manifest and may or may not work as expected for all messages. With the hydro release, almost (if not all) core ROS packages will be catkinized, and the plan is that rosserial will have the python node no longer use roslib at all.
