### ISSUE TITLE
rosserial tiva-c in i2c

### ISSUE THREAD

**Issue by altineller** [ros-drivers/rosserial#317]
Hello,

I am using rosserial with tiva-c for a while. I wonder if it can be modified to use i2c transparently?
On the tiva-c, I can open a i2c port in slave mode, and read it just like the serial port. From raspberry I can i2cset and i2cget and the tiva-c will respond. The problem is in i2c, the slave does not talk until requested. When using serial this is not the case. 

Any ideas or help greatly appreciated,

-CA

**Comment by mikepurvis** [comment]
In order to publish from the slave, it needs to be able to initiate communication with the node running the master. Some possibilities for how to deal with this might be:

- Give the slave an IO that it can use to notify the host that it has data pending (a lot of IMUs do this).
- Poll the slave on some regular interval, and just make the on-chip buffer big enough to accommodate whatever data might queue up between read instances. 

While register-oriented transports like I2C and CAN do work for rosserial, I suspect you'll have a better time if you stick with serial, USB, and TCP.
