### ISSUE TITLE
Not compatible with Timer library

### ISSUE THREAD

**Issue by yodahuang** [ros-drivers/rosserial#330]
`rosserial` is not capatible with [`Timer`](https://playground.arduino.cc/Code/Timer) library.

With multiple publisher existing, the behavior of Timer library will be unpredictable. It can either never run callback or run callback at random times.

An example will be [the code of my robot using Timer](https://github.com/RealCabot/arduino_node/tree/fcf276f0a43c271f9d810d859d7244c1d585c150), which will simply freeze itself, with heartbeat not working. After [removing Timer and using polling](https://github.com/RealCabot/arduino_node/commit/d22def45828261d496a5866d7b17750645b9d658), everything works fine.

**Comment by Baycken** [comment]
```
Sketch uses 17,594 bytes (54%) of program storage space. Maximum is 32,256 bytes.
Global variables use 1,918 bytes (93%) of dynamic memory, leaving 130 bytes for local variables. Maximum is 2,048 bytes.
```

I compiled your code (without `Timer`) on an Arduino Uno and you are really low on SRAM, I suspect the issue you are encountering has little to do with compatibility with `Timer` library, but rather the extra memory used by `Timer` library caused stack overflow into heap and broke your code. After all, you only have 130 bytes available to both stack and heap. 

And I wasn't able to build your code using `Timer`,  because it ran out of SRAM just for static objects.
```
Sketch uses 18,016 bytes (55%) of program storage space. Maximum is 32,256 bytes.
Global variables use 2,084 bytes (101%) of dynamic memory, leaving -36 bytes for local variables. Maximum is 2,048 bytes.
```

More info on https://learn.adafruit.com/memories-of-an-arduino/arduino-memories, SRAM section.

There are options to solve this problem, but I don't think it is a bug in `rosserial_arduino`.

**Comment by yodahuang** [comment]
You're exactly right. The problem is cause by SRAM.
