### ISSUE TITLE
rosserial_arduino: queue size for subscriber

### ISSUE THREAD

**Issue by fjp** [ros-drivers/rosserial#368]
Hi, is it possible to specify a queue size for a subscriber in an Arduino sketch? 

I tried to call the subscriber function of a node handle given a queue size:

```
#include <ros.h>

ros::NodeHandle  nh;

... 

void setup(){
  nh.initNode();
  nh.subscribe(sub, 1); // Error
}
...
```

But this produces the following error because the subscriber function only takes one argument for rosserial_arduino.

```
candidate expects 1 argument, 2 provided
   nh.subscribe(sub, 1);
                      ^
exit status 1
no matching function for call to 'ros::NodeHandle_<ArduinoHardware>::subscribe(ros::Subscriber<std_msgs::UInt16>&, int)'
```

**How much work is required to implement a queue parameter?**

**Comment by romainreignier** [comment]
As you can see, the `ros::Subscriber` constructor does not use such argument:
https://github.com/ros-drivers/rosserial/blob/fe1e233f39d56931b5e223c5e53a2d9c2f9fb664/rosserial_client/src/ros_lib/ros/subscriber.h#L66

The size of the input buffer (shared across all the subscribers/service clients...) is defined as a template argument of the `ros::NodeHandle` here:
https://github.com/ros-drivers/rosserial/blob/fe1e233f39d56931b5e223c5e53a2d9c2f9fb664/rosserial_client/src/ros_lib/ros/node_handle.h#L102

So depending of your hardware, you can define a larger buffer at the instantiation of the `ros::NodeHandle` here:
https://github.com/ros-drivers/rosserial/blob/fe1e233f39d56931b5e223c5e53a2d9c2f9fb664/rosserial_arduino/src/ros_lib/ros.h#L62

About adding a `queue_size` argument to the constructor of the `ros::Subscriber`, it would need a fair amount of work because as I said, there is no concept of `queue_size` per subscriber in `rosserial` implementation.
