### ISSUE TITLE
ROS 2 port

### ISSUE THREAD

**Issue by wouter-heerwegh** [ros-drivers/rosserial#589]
Hi,

Are there any plans to port rosserial to ROS2? I am aware that micro-ros exists but this does not support simpler devices like a normal arduino nano.

**Comment by mikepurvis** [comment]
No plans at all— the whole idea of rosserial is that it maintains the same serialization so that the "server" side of it is just a pass-thru. If you want to keep using ROS 1 rosserial without changing your firmware, it would make more sense to run a small ROS 1 master + an instance of ros1_bridge than to integrate message translation into any part of rosserial itself.

But yeah, the ideal path forward here is micro-ros, as that's the next-generation of the rosserial concept.
