### ISSUE TITLE
Best practice guidelines for using rosserial

### ISSUE THREAD

**Issue by tonybaltovski** [ros-drivers/rosserial#83]
Can anyone suggest any guidelines for rosserial to get the best possible results in terms of connectivity?  I often have to relaunch due to the following errors:

```
[ERROR] [WallTime: 1381939932.027978] Unable to sync with device; possible link problem or link software version mismatch such as hydro rosserial_python with groovy Arduino

[ERROR] [WallTime: 1381940238.198838] Tried to publish before configured, topic id 125
```

But after relaunching a third or forth time, the publishers and subscribers will setup correctly.  I always remake my ros_lib for every update of rosserial and recompile on the actual microprocessor.  Is there a way to ensure the connection is made on the first attempt?  Also, during the connection, I get the following errors which cause disconnects: 

```
RosSerial Xbee Network
Contacting Xbees :  ['\x00\x01']
process[mocap_node-13]: started with pid [15545]
process[rviz-15]: started with pid [15579]
[INFO] [WallTime: 1381940810.215660] Note: publish buffer size is 512 bytes
[INFO] [WallTime: 1381940810.216333] Setup publisher on aq_vehicle_status [aq_flyer/VehicleStatus]
[INFO] [WallTime: 1381940810.219510] Note: subscribe buffer size is 512 bytes
[INFO] [WallTime: 1381940810.219832] Setup subscriber on aq_ctrlLite [aq_flyer/CtrlLite]
[ERROR] [WallTime: 1381940917.220255] Lost sync with device, restarting...
[INFO] [WallTime: 1381940917.306751] Packet Failed :  Failed to read msg data
[INFO] [WallTime: 1381940917.307713] msg len is 0
[ERROR] [WallTime: 1381940917.313946] Mismatched protocol version in packet: lost sync or rosserial_python is from different ros release than the rosserial client
[INFO] [WallTime: 1381940917.315247] Protocol version of client is Rev 0 (rosserial 0.4 and earlier), expected Rev 1 (rosserial 0.5+)
[ERROR] [WallTime: 1381940989.737224] Lost sync with device, restarting...
[ERROR] [WallTime: 1381941025.531070] Lost sync with device, restarting...
[INFO] [WallTime: 1381941025.626670] Setup publisher on aq_vehicle_status [aq_flyer/VehicleStatus]
[INFO] [WallTime: 1381941025.628243] Setup subscriber on aq_ctrlLite [aq_flyer/CtrlLite]


```

Would this have to do with rosserial_xbee or poor implementation on the end of the microprocessor or even my ROS setup being incorrect?  Any suggestions are more then welcome.

Thank you in advance,
- Tony

**Comment by PaulBouchier** [comment]
This looks like an Xbee communication/timing problem. I don't have an xbee and haven't worked with it so can't help much.

"Unable to sync with device; possible link problem or link software version mismatch" happens when rosserial_python starts but doesn't receive a message from the client within the timeout. The client must always be started first. (This happens automatically on Arduinos which start up trying to connect, but may not happen on clients like linux)

"Lost sync with device, restarting..." happens when rosserial_python doesn't receive a sync/time request from the client for the timeout period

Packet Failed :  Failed to read msg data happens when rosserial_python has read a valid header from the client but the actual size of message body read doesn't match what the header said it should be. The following line shows that the message body had not been received when rosserial_python tried to read it.

The following message: "Mismatched protocol version in packet: lost sync or rosserial_python is from different ros release" happens when rosserial_python is looking for a header, and sees 0xff, then finds the next byte (which should be 0xfe) is not the expected value. I think what happened here is the body was stuck in xbee somewhere, so rosserial_python gave up on that message, then the message body came through but by then rosserial_python was looking for a header, so trying to interpret the message body as a header.

Then you have a couple more "Lost sync" messages indicating timeout waiting for a message.

It just sounds like your radios are slow or dropping packets.

Paul

**Comment by tonybaltovski** [comment]
I've tried adjusting the baud rate however, the Arduino does not operate well at 115200.  The highest baud rate seems to be 1111111 but I don't believe rosserial supports that rate.  I will try using a linux based dev board like the Beaglebone Black.  Do you recommend Angstrom or Ubuntu?

**Comment by PaulBouchier** [comment]
This doesn't seem like a baud-rate mismatch - if it were - it wouldn't work at all. It seems like a bad radio communication problem that involves packetization boundaries. Here's a link where someone's reporting similar problems and people suggest settings changes. One of the best suggestions is to try it over a serial link. That will show whether it's an xbee problem, or something else.

BTW, rosserial_python supports any baud rate that the ros system supports. Take a look at the parameters you can invoke it with. It supports private parameters of baud rate & port name. You can set these by launching it from a launch file.

I think your last question about Beaglebone black with Angstrom or Ubuntu refers to using the Beaglebone as a rosserial client. If you use Ubuntu, in theory you can install ROS on it and not even have to use rosserial. Other than that, it shouldn't make a difference, but you could consider wifi instead of xbee if you go linux, and use rosserial_embeddedlinux.

**Comment by tonybaltovski** [comment]
Does the baud rate have to be set in the Arduino code as well or will it be set when the node is initialized? The link you posted does not work.

I installed ROS on the Beaglebone Black but roslisp will not install and I am having problems with my wifi dongles but this isn't related to rosserial.

Thank you for your help Paul.

**Comment by PaulBouchier** [comment]
As far as I can tell from the code, there isn't an API to change the baud rate on the arduino - node_handle seems to cause it to always be 57600. So ignore my comment about being able to set the baud rate in rosserial_python - it was off-base in a couple of ways - not only is it irrelevant to arduino serial, but it's irrelevant to xbee, because according to the wiki page at http://wiki.ros.org/rosserial_xbee and it's tutorials (which I presume you're following), you don't use rosserial_python for an xbee link - you use xbee_network.py. Sorry for the bum steer - I'm unfamiliar with xbee.

**Comment by tonybaltovski** [comment]
No worries, it can be changed to the standard baud rates but not the custom one of 111,111.  I switched to a wired connection for the time being.

Thanks for all your help Paul.

**Comment by mehtajaghvi** [comment]
I am using an ultasound sensor from the examples. I get the serial port read error and also the Package failed error. Any idea why is that happening

**Comment by mikepurvis** [comment]
Hi @mehtajaghvi, this is a closed issue. Please open a new one and describe in more detail what commands you are running and what error you see. Please also check that you have the correct permissions for your serial port.
