### ISSUE TITLE
Arduino Due will not compile

### ISSUE THREAD

**Issue by FriedCircuits** [ros-drivers/rosserial#85]
With the most recent build and Arduino IDE 1.5.2 or 1.5.4 I receive 

C:\Users\user\Documents\Arduino\libraries\ros_lib/ArduinoHardware.h: In constructor 'ArduinoHardware::ArduinoHardware()':
C:\Users\user\Documents\Arduino\libraries\ros_lib/ArduinoHardware.h:62: error: 'Serial0' was not declared in this scope

I changed 
# if defined(USBCON)

```
  /* Leonardo support */
  iostream = &Serial; (was &Serial1) 
```
# else

```
  iostream = &Serial;
```
# endif

Now it compiles and tested working on Serial0

**Comment by PaulBouchier** [comment]
When I compile Blink from ros_lib in arduino-1.5.4 on linux I get a different library error. Changing Serial1 to Serial doesn't eliminate the error.

In file included from /home/bouchier/Arduino/libraries/ros_lib/ros.h:39,
                 from Blink.pde:6:
/home/bouchier/Arduino/libraries/ros_lib/ArduinoHardware.h: In constructor 'ArduinoHardware::ArduinoHardware()':
/home/bouchier/Arduino/libraries/ros_lib/ArduinoHardware.h:62: error: cannot convert 'USARTClass_' to 'UARTClass_' in assignment

**Comment by FriedCircuits** [comment]
Oops that is the error I got, I pasted the wrong error.

**Comment by FriedCircuits** [comment]
I just tried it again on another computer that has a fresh install and changing to iostream = &Serial; worked.

**Comment by PaulBouchier** [comment]
I think the root of the problem is that rosserial hard-codes which serial port to use, and if there's a USB-serial available (#if defined(USBCON)), hardcodes it to Serial1, #else Serial. As Arduino grows up and there are more variants, with more serial ports, it should be possible to specify which serial port to use. That way, on Arduino Due or Mega, you could choose to run rosserial over Serial3, or any other serial port (or USB serial, if you want).

On EmbeddedLinux, this is accomplished through allowing NodeHandle.init() to specify the port name. However, on Arduino, the serial ports are different instances, and possibly different types, vs. on linux where it's not OO and it's just a file descriptor.

node_handle.h instantiates Hardware, which is either ArduinoHardware or EmbeddedLinuxHardware, and I need to find a way to allow the user to instantiate it calling something other than the default constructor, and to supply arguments of the iostream that should be used. The right constructors are available to allow passing in an Arduino iostream object - I need to figure out how to do that. @mikeferguson if you're monitoring and can point me in the right direction I'd welcome it, otherwise I'll figure it out. This is deep templated C++.

**Comment by Unchapped** [comment]
I'm having this same issue with the Due, @FriedCircuits fix works, but it'd be really nice to choose a port with NodeHandle.init() (especially as the Due has 3 or 4 UARTs to choose from).
